---
title: "Performance"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

This makes the LUCAS ARTEMIS figure
```{r}
library(here)
library(data.table)
library(tidyverse)
library(devtools)
library(ggplot2)
library(ggpubr)
library(cowplot)
library(RColorBrewer)
library(pROC)
load_all(here("output","useful.stuff.aa"))


colors<-c("darkblue","steelblue")

dat<-fread(here("data","All_LCr_Clinical_Metadata_withscores.csv"))

dat$name<-dat$type
```

```{r liver_set, echo=FALSE, fig.width=12, fig.height=12, dev=c("png", "pdf")}

data<-dat %>% select(-V1) %>% filter(training=="Discovery") %>% filter(type != "Liver Disease/Early Fibrosis")
data<-data %>% mutate(type=if_else(type3=="Non-Cirrhotic Controls","healthy","cancer"))
data$type<-factor(data$type,levels=c("healthy","cancer"))
c2<-format_roc(data$type,data$score,"")
c2$model<-"Advanced Fibrosis/Cirrhosis vs. No Known Liver Disease"
c2$type<-paste0("Advanced Fibrosis/Cirrhosis: ",round(roc(data$type,data$score)$auc[1],2)," (95% CI: ",round(roc(data$type,data$score,ci=T)$ci[1],2) ,"-",round(roc(data$type,data$score,ci=T)$ci[3],2) ,")")
#r1$type<-sapply(str_split(r1$type,": "),"[",2)
r1<-c2
r1<-r1 %>% group_by(model,type) %>% arrange(sens)


data<-dat %>% select(-V1) %>% filter(training=="Discovery") %>% filter(type != "Advanced Fibrosis/Cirrhosis")
data<-data %>% mutate(type=if_else(type2=="No Known Liver Disease","healthy","cancer"))
data$type<-factor(data$type,levels=c("healthy","cancer"))
c2<-format_roc(data$type,data$score,"")
c2$model<-"Liver Disease/Early Fibrosis vs. No Known Liver Disease"
c2$type<-paste0("Liver Disease/Early Fibrosis: ",round(roc(data$type,data$score)$auc[1],2)," (95% CI: ",round(roc(data$type,data$score,ci=T)$ci[1],2) ,"-",round(roc(data$type,data$score,ci=T)$ci[3],2) ,")")
#r1$type<-sapply(str_split(r1$type,": "),"[",2)
r1<-rbind(r1,c2)
r1<-r1 %>% group_by(model,type) %>% arrange(sens)



names(colors) <- c(unique(r1$type))

r1$type<-factor(r1$type,levels=unique(r1$type))

A <- r1 %>%
    ggplot(aes(spec, sens, group=type)) +
    geom_line(aes(color=type), size=1.1) +
    scale_x_reverse(expand=c(0, 0.01),
                    breaks=c(0, 0.25, 0.5, 0.80, 1),
                    labels=as.character(
                        c("0", ".25", ".50", ".80", "1.0"))) +
    scale_y_continuous(expand=c(0, 0.01),
                       breaks=c(0, 0.25, 0.5, 0.75, 1),
                       labels=as.character(
                           c("0", ".25", ".50", ".75", "1.0"))) +
    scale_color_manual(values=colors) +
    theme_classic(base_size=35) +
    theme(panel.grid=element_blank(),
          legend.position=c(.6,.25),
          aspect.ratio=0.8,
          legend.text.align=0,
          legend.text=element_text(size=22),
          legend.title=element_text(size=22)) +
    xlab("Specificity") + ylab("Sensitivity") + 
    guides(color=guide_legend(title="AUC: (95% CI)", hjust=0)) + theme( strip.background = element_blank(), plot.title = element_text(hjust = 0.5))+ggtitle("Discovery Cohort")

C3<-ggdraw(A)#+draw_plot(B,.5,.2,.4,.4)

C3



```




