---
title: "Fragmentation profiles"
site: workflowr::wflow_site
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
chunk_output_type: console
---

```{r caching, echo=FALSE}
knitr::opts_chunk$set(autodep = TRUE)
```

```{r packages, echo=FALSE, message=FALSE, warning=FALSE}
library(ggplot2)
library(magrittr)
library(tidyverse)
library(fs)
library(grid)
library(data.table)
library(cowplot)
library(devtools)
library(here)
library(readxl)
library(cowplot)
library(ggpubr)

# 2 lines below added because of some idiosyncrasies of linux
options(bitmapType="cairo")
Sys.setenv(MKL_THREADING_LAYER="GNU")
```

```{r admixture, echo=FALSE, fig.width=12, fig.height=4, dev=c("png", "pdf")}

dat<-fread(here("data","deconvolution_admixture.csv"))
dat<-dat[,2:6]
dat$V1<-gsub("moss_","",dat$V1)
dat$V1<-gsub("loyfer_","",dat$V1)
dat$V1<-gsub("-META","",dat$V1)
dat$V1<-gsub("_","-",dat$V1)
dat$V1<-gsub("-","\n",dat$V1)

dat<-dat %>% gather(key=mix,value=perc,-V1)


#dat<-dat %>% mutate(cell_type=if_else(V1 %in% c("Blood\nMonocytes","Liver\nMacrophages"),"Monocytes/Macrophages",V1))

dat<-dat %>% mutate(cell_type=if_else(V1 %in% c("Blood\nT\nCD4","Blood\nT\nCD8"),"Blood\nT",V1))

dat<-dat %>% group_by(mix,cell_type) %>% summarize(perc=sum(perc))

#dat$cell_type<-dat$V1

dat<-dat %>% mutate(mix=if_else(mix=="buffy100_buffy100","Buffy Coat",mix))
dat<-dat %>% mutate(mix=if_else(mix=="liver100_liver100","Bulk Liver Tissue",mix))
dat<-dat %>% mutate(mix=if_else(mix=="lab90_10_lab90_10","90:10 Buffy Coat:Liver Admixture",mix))
dat<-dat %>% mutate(mix=if_else(mix=="Expected","Expected Proportions in Admixture",mix))

dat$mix<-factor(dat$mix,levels=c("Bulk Liver Tissue","Buffy Coat","90:10 Buffy Coat:Liver Admixture","Expected Proportions in Admixture"))

ggplot(dat %>% filter(mix != "Expected Proportions in Admixture"),aes(x=mix,y=perc/100,color=mix))+theme_classic()+scale_color_manual(values=c("darkblue","gray50","steelblue"))+ylab("Proportion of DNA")+xlab("")+theme(legend.position="bottom",axis.text.x=element_blank(),strip.background = element_blank())+geom_segment(aes(y=0,yend=perc/100),linewidth=.5,position=position_dodge(width=1))+facet_grid(.~cell_type)+labs(color="")+geom_point(position=position_dodge(width=1)) + 
  geom_segment(data=dat %>% filter(mix == "Expected Proportions in Admixture") %>% mutate(mix="90:10 Buffy Coat:Liver Admixture"),aes(y=perc/100,x=2.5,xend=3.5),linetype="dashed",color="black")
#+geom_violin(data=dat %>% filter(mix == "Simulated Proportions in Admixture") %>% mutate(mix="90:10 Buffy Coat:Liver Admixture"),aes(y=perc/100),color="steelblue",alpha=.25)

write.csv(dat,here("output","15D_Data.csv"))


```


