---
title: "About"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

This project is a workflowr repository containing code needed to
generate all figures and analyses in Annapragada et. al., 2025 - “Cell-free DNA fragmentomes as molecular biomarkers of liver cirrhosis and other human diseases”. Please refer to the README in the top level directory for additional details.

```{r}
library(here)
library(data.table)
library(tidyverse)
library(devtools)
library(ggplot2)
library(ggpubr)
library(cowplot)
library(readxl)
load_all(here("output","useful.stuff.aa"))

library(plyr)
library(dplyr)
library(devtools)
library(tidyverse)
library(data.table)
library(here)
library(readxl)
library(ggpubr)
library(ggrepel)
library(caret)
library(glmnet)
library(recipes)
library(devtools)

library(ggplot2)
library(magrittr)
library(tidyverse)
library(fs)
library(grid)
library(data.table)
library(cowplot)
library(devtools)
library(here)
library(readxl)
library(cowplot)
library(ggpubr)



library(here)
library(devtools)
library(grid)
library(gridExtra)
library(gtools)
library(tidyverse)
library(mvtnorm)
library(magrittr)
library(ggplot2)
library(epiR)
library(readxl)
library(data.table)
library(patchwork)
library(cowplot)

library(here)
library(data.table)
library(tidyverse)
library(devtools)
library(ggplot2)
library(ggpubr)
library(cowplot)
library(viridis)
library(pROC)
library(readxl)

library(ggplot2)
library(magrittr)
library(tidyverse)
library(fs)
library(grid)
library(data.table)
library(cowplot)
library(devtools)
library(here)
library(readxl)
library(circlize)

library(ggplot2)
library(magrittr)
library(tidyverse)
library(fs)
library(grid)
library(data.table)
library(cowplot)
library(devtools)
library(here)
library(readxl)
library(ggpubr)
library(pROC)

library(plyr)
library(dplyr)
library(devtools)
library(tidyverse)
library(data.table)
library(here)
library(readxl)
library(ggpubr)
library(ggrepel)
library(caret)
library(glmnet)
library(recipes)
library(devtools)



library(here)
library(data.table)
library(tidyverse)
library(devtools)
library(ggplot2)
library(ggpubr)
library(cowplot)
library(RColorBrewer)
library(readxl)
library(pROC)

```



```{r info}
sessionInfo()
```
